# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedinfo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schedinfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fschedinfo.proto\x12\x0cschedinfo.v1\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\xd8\x01\n\x08TaskInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12)\n\x06policy\x18\x03 \x01(\x0e\x32\x19.schedinfo.v1.SchedPolicy\x12\x14\n\x0c\x63pu_affinity\x18\x04 \x01(\x04\x12\x0e\n\x06period\x18\x05 \x01(\x05\x12\x14\n\x0crelease_time\x18\x06 \x01(\x05\x12\x0f\n\x07runtime\x18\x07 \x01(\x05\x12\x10\n\x08\x64\x65\x61\x64line\x18\x08 \x01(\x05\x12\x0f\n\x07node_id\x18\t \x01(\t\x12\x11\n\tmax_dmiss\x18\n \x01(\x05\"G\n\tSchedInfo\x12\x13\n\x0bworkload_id\x18\x01 \x01(\t\x12%\n\x05tasks\x18\x02 \x03(\x0b\x32\x16.schedinfo.v1.TaskInfo\"k\n\tFaultInfo\x12\x13\n\x0bworkload_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x11\n\ttask_name\x18\x03 \x01(\t\x12%\n\x04type\x18\x04 \x01(\x0e\x32\x17.schedinfo.v1.FaultType*+\n\x0bSchedPolicy\x12\n\n\x06NORMAL\x10\x00\x12\x08\n\x04\x46IFO\x10\x01\x12\x06\n\x02RR\x10\x02*#\n\tFaultType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x44MISS\x10\x01\x32U\n\x10SchedInfoService\x12\x41\n\x0c\x41\x64\x64SchedInfo\x12\x17.schedinfo.v1.SchedInfo\x1a\x16.schedinfo.v1.Response\"\x00\x32P\n\x0c\x46\x61ultService\x12@\n\x0bNotifyFault\x12\x17.schedinfo.v1.FaultInfo\x1a\x16.schedinfo.v1.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedinfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDPOLICY']._serialized_start=462
  _globals['_SCHEDPOLICY']._serialized_end=505
  _globals['_FAULTTYPE']._serialized_start=507
  _globals['_FAULTTYPE']._serialized_end=542
  _globals['_RESPONSE']._serialized_start=33
  _globals['_RESPONSE']._serialized_end=59
  _globals['_TASKINFO']._serialized_start=62
  _globals['_TASKINFO']._serialized_end=278
  _globals['_SCHEDINFO']._serialized_start=280
  _globals['_SCHEDINFO']._serialized_end=351
  _globals['_FAULTINFO']._serialized_start=353
  _globals['_FAULTINFO']._serialized_end=460
  _globals['_SCHEDINFOSERVICE']._serialized_start=544
  _globals['_SCHEDINFOSERVICE']._serialized_end=629
  _globals['_FAULTSERVICE']._serialized_start=631
  _globals['_FAULTSERVICE']._serialized_end=711
# @@protoc_insertion_point(module_scope)
