# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import schedinfo_pb2 as schedinfo__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in schedinfo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedInfoServiceStub(object):
    """SchedInfoService in Timpani-O
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSchedInfo = channel.unary_unary(
                '/schedinfo.v1.SchedInfoService/AddSchedInfo',
                request_serializer=schedinfo__pb2.SchedInfo.SerializeToString,
                response_deserializer=schedinfo__pb2.Response.FromString,
                _registered_method=True)


class SchedInfoServiceServicer(object):
    """SchedInfoService in Timpani-O
    """

    def AddSchedInfo(self, request, context):
        """Add a new SchedInfo
        From Pullpiri to Timpani-O
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSchedInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSchedInfo,
                    request_deserializer=schedinfo__pb2.SchedInfo.FromString,
                    response_serializer=schedinfo__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schedinfo.v1.SchedInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('schedinfo.v1.SchedInfoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedInfoService(object):
    """SchedInfoService in Timpani-O
    """

    @staticmethod
    def AddSchedInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedinfo.v1.SchedInfoService/AddSchedInfo',
            schedinfo__pb2.SchedInfo.SerializeToString,
            schedinfo__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FaultServiceStub(object):
    """FaultService in Pullpiri
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyFault = channel.unary_unary(
                '/schedinfo.v1.FaultService/NotifyFault',
                request_serializer=schedinfo__pb2.FaultInfo.SerializeToString,
                response_deserializer=schedinfo__pb2.Response.FromString,
                _registered_method=True)


class FaultServiceServicer(object):
    """FaultService in Pullpiri
    """

    def NotifyFault(self, request, context):
        """Notify a fault
        From Timpani-O to Pullpiri
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyFault': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyFault,
                    request_deserializer=schedinfo__pb2.FaultInfo.FromString,
                    response_serializer=schedinfo__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schedinfo.v1.FaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('schedinfo.v1.FaultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaultService(object):
    """FaultService in Pullpiri
    """

    @staticmethod
    def NotifyFault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedinfo.v1.FaultService/NotifyFault',
            schedinfo__pb2.FaultInfo.SerializeToString,
            schedinfo__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
